//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define IDI_ICON1                       101
#define IDR_MENU1                       103
#define IDR_MAINFRAME                   103
#define IDD_DLGABOUT                    104
#define IDR_ACCELERATOR1                105
#define IDR_ACC_MAINFRAME               105
#define IDB_LED_OFF                     114
#define IDB_LED_ON                      115
#define IDB_STEP_BK                     116
#define IDB_STEP1A                      117
#define IDB_STEP2A                      119
#define IDB_SLIDER_BK                   121
#define IDB_CUTOFF                      122
#define IDB_ENV                         123
#define IDB_RESO                        124
#define IDB_TUNE                        125
#define IDB_OSC_LEDOFF                  126
#define IDB_OSC2                        127
#define IDB_OSC3                        128
#define IDB_OSC1                        129
#define IDB_OSC_LEDON                   130
#define IDB_SUBSTAIN                    131
#define IDB_DECAY                       132
#define IDB_RELEASE                     133
#define IDB_ATTACK                      134
#define IDD_SETTINGS                    138
#define IDB_VOLUME_BK                   140
#define IDB_LED_GREEN                   142
#define IDB_LED_RED                     143
#define IDB_SPEED                       144
#define IDB_PLAY_UP                     145
#define IDB_PLAY_DOWN                   147
#define IDB_RIGHT_ON                    157
#define IDB_LCD9                        159
#define IDB_LCD1                        160
#define IDB_LCD2                        161
#define IDB_LCD3                        162
#define IDB_LCD4                        163
#define IDB_LCD5                        164
#define IDB_LCD6                        165
#define IDB_LCD7                        166
#define IDB_LCD8                        167
#define IDB_LCD0                        168
#define IDB_PANEL_PLAY_LED_ON           169
#define IDB_PLAY_ON                     170
#define IDB_PANEL_BPM                   171
#define IDB_PANEL_CUR                   172
#define IDB_PANEL_MAX                   173
#define IDB_PANEL_PLAY                  174
#define IDB_PANEL_PLAY_LED_OFF          175
#define IDB_PLAY_OFF                    176
#define IDB_SHUFFLE                     177
#define IDB_SPLASH                      179
#define IDD_SYSTEM                      180
#define IDB_REV_ON                      207
#define IDB_LOAD_ON                     208
#define IDB_LOOP_OFF                    209
#define IDB_LOOP_ON                     210
#define IDB_REV_OFF                     211
#define IDB_LOAD_OFF                    212
#define IDB_MUTE_OFF                    216
#define IDB_MUTE_ON                     217
#define IDB_LOOPMODE_ON                 218
#define IDB_LOOPMODE_OFF                219
#define IDB_FILTER_LOW                  220
#define IDB_FILTER_HIGH                 221
#define IDB_SKNOB_RED                   258
#define IDB_SKNOB_GREEN                 259
#define IDB_SKNOB_BLUE                  260
#define IDB_LABEL                       261
#define IDB_FXKNOB                      263
#define IDB_LITTLEKNOB                  264
#define IDB_LITTLEKNOB_RED              265
#define IDB_REC_ON                      267
#define IDB_REC_OFF                     272
#define IDB_PANEL                       275
#define IDB_PANEL2                      278
#define IDD_DLG_RECORD                  281
#define IDD_PROGRESS_DIALOG             282
#define IDB_FX_OFF                      288
#define IDB_FX_ON                       289
#define IDD_DLG_SYNTHSTRUCTURE          291
#define IDD_DLG_DRUMBOX                 292
#define IDB_MROC_LOGO                   293
#define IDD_DLG_SYNTHCOUNT              294
#define IDB_MSYNTH_SPLASH               295
#define IDB_SKNOB_GRAY                  296
#define IDD_TRANSFORMER_COLLECTION_EDITOR 300
#define IDB_MIXER_KNOB                  301
#define IDB_MIXER_LINE                  302
#define IDR_ACC_ARRANGE_FRAME           303
#define IDB_BLUE_SCALED                 304
#define IDB_KEYBOARD                    306
#define IDC_PEN                         307
#define IDB_SELECT_MODE_OFF             312
#define IDB_DRAW_MODE_ON                313
#define IDB_DRAW_MODE_OFF               314
#define IDB_SELECT_MODE_ON              315
#define IDR_ACC_NOTE_FRAME              316
#define IDR_BEATBOX_EDITOR              317
#define IDC_GLOW                        319
#define IDB_GLOW_MODE_OFF               320
#define IDB_GLOW_MODE_ON                321
#define IDC_CUT                         322
#define IDB_CUT_MODE_OFF                323
#define IDB_CUT_MODE_ON                 324
#define IDB_EQSLIDER_OFF                335
#define IDB_EQSLIDER_ON                 336
#define IDB_ON                          337
#define IDB_OFF                         338
#define IDB_MUTE2_ON                    339
#define IDB_MUTE2_OFF                   340
#define IDR_SYNTH_EDITOR                347
#define IDB_STOP_ON                     348
#define IDB_RECORD_OFF                  350
#define IDB_RECORD_ON                   351
#define IDB_STOP_OFF                    352
#define IDB_ARROW                       390
#define IDB_CUTTER                      391
#define IDB_GLOW                        392
#define IDB_PEN                         393
#define IDI_DOC_ICON                    394
#define IDB_SYS4                        399
#define IDB_SYS0                        400
#define IDB_SYS1                        401
#define IDB_SYS2                        402
#define IDB_SYS3                        403
#define IDB_SYSDBLDOT                   404
#define IDB_SYS5                        405
#define IDB_SYS6                        406
#define IDB_SYS7                        407
#define IDB_SYS8                        408
#define IDB_SYS9                        409
#define IDR_CONTROL_CONTEXT             412
#define IDB_ICON_STOP_ON                439
#define IDB_ICON_AUTO_ON                440
#define IDB_ICON_PLAY_OFF               441
#define IDB_ICON_PLAY_ON                442
#define IDB_ICON_RECORD_OFF             443
#define IDB_ICON_RECORD_ON              444
#define IDB_ICON_STOP_OFF               445
#define IDB_ICON_AUTO_OFF               446
#define ID_DEBUG_STATISTICS449          449
#define ID_Menu                         450
#define IDR_MENU2                       451
#define IDR_AUDIOCHANNELEDITOR_MENU     451
#define ID_FILE_IMPORTFILE              452
#define IDR_AUDIOCHANNEL_EDITOR         453
#define ID_FILE_IMPORTFILE454           454
#define ID_INSTRUMENT_CREATEAUDIOCHANNEL 455
#define IDB_BITMAP1                     465
#define IDB_ICON_AUDIO                  465
#define IDB_BITMAP2                     466
#define IDB_ICON_BEATBOX                466
#define IDB_ICON_SYNTH                  467
#define ID_DYNAMICS                     469
#define ID_DYNAMICS_DYNGO               470
#define IDC_DXDEVICE                    1008
#define IDC_S0                          1014
#define IDC_CERTIFIED                   1015
#define IDC_S1                          1016
#define IDC_CONTINOUS                   1017
#define IDC_CONTINIOUS2                 1018
#define IDC_PB16                        1019
#define IDC_PRIMARY                     1020
#define IDC_PB8                         1021
#define IDC_CONTINIOUS3                 1022
#define IDC_SB16                        1023
#define IDC_PRIMARY2                    1024
#define IDC_SB8                         1025
#define IDC_CONTINIOUS4                 1026
#define IDC_STEPWIDTH                   1027
#define IDC_PRIMARY3                    1028
#define IDC_BPM                         1029
#define IDC_CONTINIOUS5                 1030
#define IDC_SAMPLERATE                  1031
#define IDC_PRIMARY4                    1032
#define IDC_SLEEP                       1033
#define IDC_CONTINIOUS6                 1034
#define IDC_BUFFERLENGTH                1035
#define IDC_WINDOWSVERISON              1036
#define IDC_VERSION                     1038
#define IDC_RADIO1                      1039
#define IDC_RADIO2                      1040
#define IDC_PROGRESS1                   1040
#define IDC_RADIO3                      1041
#define IDC_STATIC_BUFFERLENGTH         1041
#define IDC_STATIC_BUFFERLENGTH2        1042
#define IDC_COMBO_BUFFERLENGTH          1044
#define IDC_CHECK_STICKYFOCUS           1045
#define IDC_COMBO_SOURCE                1056
#define IDC_LIST_TRANSFORMER            1057
#define IDC_BUTTON_ADD                  1058
#define IDC_BUTTON_REMOVE               1059
#define IDC_BUTTON_UP                   1060
#define IDC_BUTTON_DOWN                 1061
#define IDC_COMBO_REGISTEREDTRANSFORMERS 1062
#define IDC_EDIT_CHANNELCOUNT           1063
#define IDC_EDIT_SYNTHCOUNT             1065
#define IDC_COMBO_ENGINE                1067
#define IDC_STATIC_ENGINE               1068
#define IDC_STATIC_LINK                 1069
#define IDC_STATIC_LINK_APACHE          1070
#define IDC_COPYRIGHT                   1075
#define IDC_EDIT1                       1076
#define IDC_COMBO1                      1080
#define IDC_CPU_COMBO                   1080
#define IDC_ENABLE_WATCHDOG             1081
#define IDC_BUTTON1                     1082
#define IDC_BUTTON_CANCEL               1082
#define IDC_TAB1                        1083
#define ID_EXPORT_SONG                  40004
#define ID_FILE_EXIT                    40006
#define ID_PATTERN_COPY                 40007
#define ID_PATTERN_PASTE                40008
#define ID_PATTERN_CUT                  40009
#define ID_ABOUT_ABOUT                  40010
#define ID_ABOUT_SYSTEM                 40011
#define ID_SETTINGS_SETTINGS            40016
#define ID_FILE_SAVESAMPLEBANK          40017
#define ID_FILE_OPENSAMPLEBANK          40018
#define ID_NEW_SONG                     40020
#define ID_PLAY                         40021
#define ID_EXPORT                       40025
#define ID_QUIT                         40027
#define ID_DRUMBOX_SETTING              40029
#define ID_SYNTHCOUNT                   40030
#define ID_SYNTH_REMOVESYNTH            40038
#define ID_SYNTH_CLEARPATTERN           40039
#define ID_SYNTH_CLEARALLPATTERNS       40041
#define ID_SHOW_BEATBOX                 40042
#define ID_ABOUT_HELP                   40043
#define ID_VIEW_SHOWMIXER               40044
#define ID_SHOW_MIXER                   40044
#define ID_SHOW_ARRANGE                 40045
#define ID_DELETE                       40046
#define ID_CREATESYNTH                  40047
#define ID_CREATEBEATBOX                40048
#define ID_SAMPLEBANK_NEW               40049
#define ID_SAMPLEBANK_SAVE              40050
#define ID_SAMPLEBANK_SAVEAS            40051
#define ID_SAMPLEBANK_OPEN              40052
#define ID_CHANNEL_DELETE               40053
#define ID_CHANNEL_CREATE               40054
#define ID_CHANNEL_SETNUMBEROFCHANNELS  40055
#define ID_COPY                         40056
#define ID_PASTE                        40057
#define ID_CUT                          40058
#define ID_EDIT_RESET                   40063
#define ID_EDIT_EDIT                    40064
#define ID_RESET                        40065
#define ID_VIEW_FXRACK                  40066
#define ID_SHOW_FXRACK                  40066
#define ID_FILE_CLOSE_WINDOW            40069
#define ID_SAMPLEBANK_CLOSEWINDOW       40070
#define ID_SHOW_HELP                    40074
#define ID_ADDTOAUTOMATION              40075
#define ID_DEBUG_STATISTICS             40076
#define ID_DEBUG_CONTROLREGISTRY        40077
#define ID_MENU_REMOVEALLEVENTS         40078
#define ID_RESETTODEFAULT               40079
#define ID_REMOVEFROMAUTOMATION         40080
#define ID_AUDIOCHANNEL_IMPORT          40081
#define ID_OPEN_SYNTH                   40087
#define ID_SAVE_SYNTH                   40088
#define ID_SAVE_SONG                    40089
#define ID_EXIT                         40090
#define ID_OPEN_SONG                    40091
#define ID_SAVE_SONG_AS                 40092

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        471
#define _APS_NEXT_COMMAND_VALUE         41081
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
